# Generated by Django 3.0.3 on 2020-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
